CREATE TABLE IF NOT EXISTS students (
  student_id VARCHAR(36) NOT NULL,
  name VARCHAR(100) NOT NULL,
  furigana VARCHAR(100) NOT NULL,
  nickname VARCHAR(100) DEFAULT NULL,
  email VARCHAR(100) NOT NULL,
  city VARCHAR(100) DEFAULT NULL,
  age INT DEFAULT NULL,
  gender VARCHAR(100) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (student_id)
);

CREATE TABLE IF NOT EXISTS students_courses (
  course_id VARCHAR(36) NOT NULL,
  student_id VARCHAR(36) NOT NULL,
  course_name VARCHAR(100) NOT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS students_courses_status (
status_id VARCHAR(36) NOT NULL,
course_id VARCHAR(36) NOT NULL,
status VARCHAR(50) NOT NULL
PRIMARY KEY (status_id)
);